services:
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 <em># Poll every 60 seconds</em>
      - WATCHTOWER_CONTAINERS=express-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower

  express-app:
    container_name: express-app
    build: .
