services:
  watchtower:
    image: beatkind/watchtower:latest
    environment:
      WATCHTOWER_POLL_INTERVAL: "60"
      WATCHTOWER_CLEANUP: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower

  express-app:
    image: joonanzo/express-app:latest
    ports:
      - "3000:8080"
    container_name: express-app
    build: .
